import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { Issues, apolloClient } from '../component/client'
import { ApolloProvider } from '@apollo/client'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js GitHub Issues Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1>GitHub Issues Blog</h1>
      </header>

      <main className={styles.main}>
        <div className={styles.card}>
          <ApolloProvider client={apolloClient}>
            <Issues />
          </ApolloProvider>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>&copy;2021 YutoUrushima All Rights Reserved.</p>
      </footer>
    </div>
  )
}