import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { SNS } from '../component/sns'
import { ICON } from '../component/icon'
import { Issues, apolloClient } from '../component/client'
import { ApolloProvider } from '@apollo/client'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Next.js GitHub Issues Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className={styles.headerInner}>
          <div className="pc">
            <ICON/>
          </div>
          <h1>GitHub Issues Blog</h1>
          <div className="pc">
            <SNS/>
          </div>
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.card}>
          <ApolloProvider client={apolloClient}>
            <Issues />
          </ApolloProvider>
        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.footerInner}>
          <div className={styles.toTop}>
            <Link href="/">
              <a>
                To Top
              </a>
            </Link>
          </div>
          <p>&copy;2021 YutoUrushima All Rights Reserved.</p>
        </div>
      </footer>
    </div>
  )
}